Traceback (most recent call last):
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#######################################################################################
# Data are saved in .csv files; this block loads and sorts the various data sets      #
#######################################################################################

DATA1, HEADER = readdlm("BR02A.csv", ',', Any, '\n', header = true)
DATA2, HEADER = readdlm("BR02B.csv", ',', Any, '\n', header = true)
DATA1 = Float64.(DATA1)
DATA2 = Float64.(DATA2)

t1  = DATA1[:, 1]
NA1 = DATA1[:, 2]
NB1 = DATA1[:, 3]
CA1 = DATA1[:, 4]
CB1 = DATA1[:, 5]
aA1 = DATA1[:, 6]
aB1 = DATA1[:, 7]
XA1 = DATA1[:, 8]
r1  = DATA1[:, 9]

t2  = DATA2[:, 1]
NA2 = DATA2[:, 2]
NB2 = DATA2[:, 3]
CA2 = DATA2[:, 4]
CB2 = DATA2[:, 5]
aA2 = DATA2[:, 6]
aB2 = DATA2[:, 7]
XA2 = DATA2[:, 8]
r2  = DATA2[:, 9]

##################################################################################################
# This will generate a formatted table for display purposes, not necessary for analysis          #
##################################################################################################

spacer = Array{String, 1}(UndefInitializer(), 10)
for i = 1:length(spacer)
    spacer[i] = "  "
end

pretty_table(hcat(spacer, t1[1:10], NA1[1:10], spacer, t2[1:10], NA2[1:10]), header = (["Pt/SiO2 ->", "t1 (ks)", "N_A (mol)", "Ru/SiO2 ->", "t2 (ks)", "N_A (mol)"]))
;
------------------


ArgumentError: Cannot open 'BR02A.csv': not a file

Stacktrace:
 [1] readdlm_auto(input::String, dlm::Char, T::Type, eol::Char, auto::Bool; opts::@Kwargs{header::Bool})
   @ DelimitedFiles C:\Users\jqbon\.julia\packages\DelimitedFiles\aGcsu\src\DelimitedFiles.jl:234
 [2] readdlm_auto
   @ C:\Users\jqbon\.julia\packages\DelimitedFiles\aGcsu\src\DelimitedFiles.jl:233 [inlined]
 [3] #readdlm#6
   @ C:\Users\jqbon\.julia\packages\DelimitedFiles\aGcsu\src\DelimitedFiles.jl:226 [inlined]
 [4] top-level scope
   @ In[4]:5

