Traceback (most recent call last):
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
####################################################################################
# Import batch reactor data saved in a .csv file                                   #
####################################################################################

DATA1, HEADER = readdlm("BATCH1.csv", ',', Any, '\n', header = true)
DATA1 = Float64.(DATA1)
t1    = DATA1[:, 1] #batch reaction time in seconds
CA1   = DATA1[:, 4] #concentration of A, mol/L
CB1   = DATA1[:, 5] #concentraiton of B, mol/L
XA1   = (CA0 .- CA1)/CA0 #Adequate definition of XA for a CV Batch Reactor

####################################################################################
# Generate a nicely formatted table; using for display purposes and not analysis   # 
####################################################################################

pretty_table(hcat(t1/1000, round.(CA1*1000, digits = 1), round.(CB1*1000, digits = 1), round.(XA1, digits = 2)), header = (["t (ks)", "CA (mmol/L)", "CB (mmol/L)", "XA"]))
;
------------------


ArgumentError: Cannot open 'BATCH1.csv': not a file

Stacktrace:
 [1] readdlm_auto(input::String, dlm::Char, T::Type, eol::Char, auto::Bool; opts::@Kwargs{header::Bool})
   @ DelimitedFiles C:\Users\jqbon\.julia\packages\DelimitedFiles\aGcsu\src\DelimitedFiles.jl:234
 [2] readdlm_auto
   @ C:\Users\jqbon\.julia\packages\DelimitedFiles\aGcsu\src\DelimitedFiles.jl:233 [inlined]
 [3] #readdlm#6
   @ C:\Users\jqbon\.julia\packages\DelimitedFiles\aGcsu\src\DelimitedFiles.jl:226 [inlined]
 [4] top-level scope
   @ In[5]:5

